services:
  mysql:
    image: mysql:8.0
    container_name: encuesta_mysql
    restart: always
    command: --log-bin-trust-function-creators=1  # ✅ permite crear triggers sin SUPER
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: encuesta_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/src/uploads:/usr/src/app/src/uploads   # ✅ corrección
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: encuesta_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
